steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔄 Restarting Cloud Run (NO IMAGE)..."

        gcloud run services update hello \
          --region=us-central1 \
          --project=eighth-physics-489004-b2 \
          --update-env-vars=RESTART_TRIGGER=$(date +%s)

options:
  logging: CLOUD_LOGGING_ONLY
