steps:
  - name: hashicorp/terraform:1.5.0
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform
        terraform init
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY 
